#-setting the application name
spring:
  application:
    name: FLIGHT-SERVICE

#-for registering with Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost